"""empty message

Revision ID: 97c043deae54
Revises: ac963254cdab
Create Date: 2023-05-24 00:34:39.282940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97c043deae54'
down_revision = 'ac963254cdab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credential')
    op.drop_table('form')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('header', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('field_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('secondary_color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='form_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='form_pkey')
    )
    op.create_table('credential',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credential_id', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('credential_public_key', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('current_sign_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('credential_transport', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='credential_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='credential_pkey')
    )
    # ### end Alembic commands ###
